version: "3.7"

services:
  web:
    container_name: ex1_web
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/php/8.1/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./.docker/php/8.1/php.ini:/usr/local/etc/php/conf.d/my-app.ini
    links:
    - db
  db:
    container_name: ex1_db
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - ./.docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ex1

